# Generated by Django 3.1.6 on 2021-12-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='cinema', max_length=11),
        ),
    ]
